### ISSUE TITLE
Error: Cannot find module './Aggregation'

### ISSUE THREAD

**Issue by ITWOI** [jupe/puml2code#119]
### Description

- Type: Bug 
- Related Issue: NA

---------------------------------------------------------------
## Bug

**puml2code version**

v0.7.0-19-g08a1f51

**Expected Behavior**
Works correctly after running `puml2code/bin/puml2code -i library_management_system/library_management_system.puml -l java`
**Actual Behavior**
The command produces an error.
```
Error: Cannot find module './Aggregation'
Require stack:
- /Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js
- /Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/index.js
- /Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/index.js
- /Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/cli.js
- /Users/wangyu/Documents/Experiments/UML2Code/puml2code/bin/puml2code
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at peg$c49 (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:193:48)
    at peg$parseconnectortype (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:1805:16)
    at peg$parseconnectordeclaration (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:1025:20)
    at peg$parseumlline (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:880:38)
    at peg$parseumllines (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:645:12)
    at peg$parseplantumlfile (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:493:20)
    at Object.peg$parse [as parse] (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js:4201:16)
    at /Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/index.js:4:51
    at tryCatcher (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/node_modules/bluebird/js/release/method.js:39:29)
    at module.exports (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/index.js:4:37)
    at PlantUmlToCode._toCode (/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/index.js:139:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/plantuml.js',
    '/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/parser/index.js',
    '/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/index.js',
    '/Users/wangyu/Documents/Experiments/UML2Code/puml2code/src/cli.js',
    '/Users/wangyu/Documents/Experiments/UML2Code/puml2code/bin/puml2code'
  ]
}
```

**Comment by uberfig** [comment]
same here

**Comment by niuqiang2078** [comment]
same here. 

The syntax supported by plantuml is rich, but it's strictly limited while using puml2code. I spent a lot of time getting through the grammar checks, but ended up stucking here, it's very frustrating
