### ISSUE TITLE
Unable to generate code

### ISSUE THREAD

**Issue by dcr007** [jupe/puml2code#91]
### Description

- Type: Bug 

---------------------------------------------------------------
## Bug
Unable to run the following .puclass file . i get the below error 
```
puml2code -i poc_uml.puclass -l java
Error: line: 18 column: 67: SyntaxError: Expected "|>", [ \t], ["], [*], [A-Za-z_], or [o] but ">" found.
    at PlantUmlToCode.generate (/usr/local/lib/node_modules/puml2code/src/index.js:86:15)
    at async execute (/usr/local/lib/node_modules/puml2code/src/cli.js:53:20)

```

poc_uml.puclass :

```

@startuml

class com.ondemand.myapp.splunkconsumer.api.controllers.UmlController {
    - UmlService splunkService
    + ResponseEntity<String> postSplunkRawData(String)
    + ResponseEntity<RawData> postSplunkRawData(RawData)
    + ResponseEntity<DcLogins> postSplunkData(DcLogins)
    + ResponseEntity<List<DcLogins>> findRecordBySid(String)
}
class com.ondemand.myapp.splunkconsumer.api.services.UmlService {
    - UmlRepository splunkRepository
    - DcLogins payload
    - SplunkDataRepository splunkDataRepository
    + DcLogins saveReport(DcLogins)
    + RawData saveData(RawData)
    + List<DcLogins> findBySid(String)
}
com.ondemand.myapp.splunkconsumer.api.controllers.UmlController ..> com.ondemand.myapp.splunkconsumer.api.services.UmlService
@enduml

```

-----------------------------------------------------------------

## Question

**How to fix it ?**

**Comment by zbynek** [comment]
Looks like generics are not supported
